### ISSUE TITLE
I am not able to add  route Map Hub method in global.asax file.

### ISSUE THREAD

**Issue by vinay01joshi** [turanuk/signalrgrid#1]
RouteTable.Routes.MapHubs(); 
This method is not showing in my Global.asax file ..when i create the signal-R grid .can you please help me.. 
I am using VS 2013-Web Edition.

![capture](https://f.cloud.github.com/assets/3734672/1895998/409fdd68-7b74-11e3-9811-67d99f0bbd0f.PNG)

**Comment by turanuk** [comment]
You need to follow the instructions for SignalR v2 - the code was written
using SignalR v1 - I don't think MapHubs exists anymore...

**Comment by nikhilhece2011** [comment]
MApHubs() is now depricated, you need to use owin to setup ur hubs..but if you want to use maphubs() in global.asax , you'll have to choose older version of signalR and visual studio as well..
